// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOylHow4Bg8fk0O2FbiHcxA8wq6OPkRmo',
    appId: '1:790627865650:web:5fd14b09a61565bc8b582b',
    messagingSenderId: '790627865650',
    projectId: 'grantscout-af8da',
    authDomain: 'grantscout-af8da.firebaseapp.com',
    storageBucket: 'grantscout-af8da.firebasestorage.app',
    measurementId: 'G-CLWW6049WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqc8T1C6iCm4-oSZMlg7vaIehsp8R69PE',
    appId: '1:790627865650:android:df2eae7f95d28fc28b582b',
    messagingSenderId: '790627865650',
    projectId: 'grantscout-af8da',
    storageBucket: 'grantscout-af8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_yzukTRHY0y45uwnM7zNwJnuhOvakN0',
    appId: '1:790627865650:ios:b1ebfb588790b8bb8b582b',
    messagingSenderId: '790627865650',
    projectId: 'grantscout-af8da',
    storageBucket: 'grantscout-af8da.firebasestorage.app',
    iosClientId: '790627865650-ebrcsmg705k187ek8ocfeh4f90indkth.apps.googleusercontent.com',
    iosBundleId: 'com.example.grantscoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_yzukTRHY0y45uwnM7zNwJnuhOvakN0',
    appId: '1:790627865650:ios:b1ebfb588790b8bb8b582b',
    messagingSenderId: '790627865650',
    projectId: 'grantscout-af8da',
    storageBucket: 'grantscout-af8da.firebasestorage.app',
    iosClientId: '790627865650-ebrcsmg705k187ek8ocfeh4f90indkth.apps.googleusercontent.com',
    iosBundleId: 'com.example.grantscoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOylHow4Bg8fk0O2FbiHcxA8wq6OPkRmo',
    appId: '1:790627865650:web:dfccdbe44c3dd6308b582b',
    messagingSenderId: '790627865650',
    projectId: 'grantscout-af8da',
    authDomain: 'grantscout-af8da.firebaseapp.com',
    storageBucket: 'grantscout-af8da.firebasestorage.app',
    measurementId: 'G-MQDYCQ85YK',
  );
}
